services:
  web:
    build:
      context: ./vuejs
      dockerfile: Dockerfile
    container_name: frontend
    image: frontend_image    
    volumes:
      - ./vuejs/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      